/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as homeLayoutRouteImport } from './routes/(home)/_layout'
import { Route as homeLayoutIndexRouteImport } from './routes/(home)/_layout.index'
import { Route as homeLayoutProjectsRouteImport } from './routes/(home)/_layout.projects'

const homeLayoutRoute = homeLayoutRouteImport.update({
  id: '/(home)/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const homeLayoutIndexRoute = homeLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => homeLayoutRoute,
} as any)
const homeLayoutProjectsRoute = homeLayoutProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => homeLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/projects': typeof homeLayoutProjectsRoute
  '/': typeof homeLayoutIndexRoute
}
export interface FileRoutesByTo {
  '/projects': typeof homeLayoutProjectsRoute
  '/': typeof homeLayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(home)/_layout': typeof homeLayoutRouteWithChildren
  '/(home)/_layout/projects': typeof homeLayoutProjectsRoute
  '/(home)/_layout/': typeof homeLayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/projects' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/projects' | '/'
  id:
    | '__root__'
    | '/(home)/_layout'
    | '/(home)/_layout/projects'
    | '/(home)/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  homeLayoutRoute: typeof homeLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(home)/_layout': {
      id: '/(home)/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof homeLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(home)/_layout/': {
      id: '/(home)/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof homeLayoutIndexRouteImport
      parentRoute: typeof homeLayoutRoute
    }
    '/(home)/_layout/projects': {
      id: '/(home)/_layout/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof homeLayoutProjectsRouteImport
      parentRoute: typeof homeLayoutRoute
    }
  }
}

interface homeLayoutRouteChildren {
  homeLayoutProjectsRoute: typeof homeLayoutProjectsRoute
  homeLayoutIndexRoute: typeof homeLayoutIndexRoute
}

const homeLayoutRouteChildren: homeLayoutRouteChildren = {
  homeLayoutProjectsRoute: homeLayoutProjectsRoute,
  homeLayoutIndexRoute: homeLayoutIndexRoute,
}

const homeLayoutRouteWithChildren = homeLayoutRoute._addFileChildren(
  homeLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  homeLayoutRoute: homeLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
