/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HealthRouteImport } from './routes/health'
import { Route as ApiOgRouteImport } from './routes/api/og'
import { Route as homeLayoutRouteImport } from './routes/(home)/_layout'
import { Route as homeLayoutIndexRouteImport } from './routes/(home)/_layout/index'
import { Route as homeLayoutWorkRouteImport } from './routes/(home)/_layout/work'
import { Route as homeLayoutVaultTreeArithmeticIndexRouteImport } from './routes/(home)/_layout/vault/tree-arithmetic/index'
import { Route as homeLayoutVaultElltyIndexRouteImport } from './routes/(home)/_layout/vault/ellty/index'

const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOgRoute = ApiOgRouteImport.update({
  id: '/api/og',
  path: '/api/og',
  getParentRoute: () => rootRouteImport,
} as any)
const homeLayoutRoute = homeLayoutRouteImport.update({
  id: '/(home)/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const homeLayoutIndexRoute = homeLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => homeLayoutRoute,
} as any)
const homeLayoutWorkRoute = homeLayoutWorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => homeLayoutRoute,
} as any)
const homeLayoutVaultTreeArithmeticIndexRoute =
  homeLayoutVaultTreeArithmeticIndexRouteImport.update({
    id: '/vault/tree-arithmetic/',
    path: '/vault/tree-arithmetic/',
    getParentRoute: () => homeLayoutRoute,
  } as any)
const homeLayoutVaultElltyIndexRoute =
  homeLayoutVaultElltyIndexRouteImport.update({
    id: '/vault/ellty/',
    path: '/vault/ellty/',
    getParentRoute: () => homeLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/health': typeof HealthRoute
  '/api/og': typeof ApiOgRoute
  '/work': typeof homeLayoutWorkRoute
  '/': typeof homeLayoutIndexRoute
  '/vault/ellty': typeof homeLayoutVaultElltyIndexRoute
  '/vault/tree-arithmetic': typeof homeLayoutVaultTreeArithmeticIndexRoute
}
export interface FileRoutesByTo {
  '/health': typeof HealthRoute
  '/api/og': typeof ApiOgRoute
  '/work': typeof homeLayoutWorkRoute
  '/': typeof homeLayoutIndexRoute
  '/vault/ellty': typeof homeLayoutVaultElltyIndexRoute
  '/vault/tree-arithmetic': typeof homeLayoutVaultTreeArithmeticIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/health': typeof HealthRoute
  '/(home)/_layout': typeof homeLayoutRouteWithChildren
  '/api/og': typeof ApiOgRoute
  '/(home)/_layout/work': typeof homeLayoutWorkRoute
  '/(home)/_layout/': typeof homeLayoutIndexRoute
  '/(home)/_layout/vault/ellty/': typeof homeLayoutVaultElltyIndexRoute
  '/(home)/_layout/vault/tree-arithmetic/': typeof homeLayoutVaultTreeArithmeticIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/health'
    | '/api/og'
    | '/work'
    | '/'
    | '/vault/ellty'
    | '/vault/tree-arithmetic'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/health'
    | '/api/og'
    | '/work'
    | '/'
    | '/vault/ellty'
    | '/vault/tree-arithmetic'
  id:
    | '__root__'
    | '/health'
    | '/(home)/_layout'
    | '/api/og'
    | '/(home)/_layout/work'
    | '/(home)/_layout/'
    | '/(home)/_layout/vault/ellty/'
    | '/(home)/_layout/vault/tree-arithmetic/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  HealthRoute: typeof HealthRoute
  homeLayoutRoute: typeof homeLayoutRouteWithChildren
  ApiOgRoute: typeof ApiOgRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/og': {
      id: '/api/og'
      path: '/api/og'
      fullPath: '/api/og'
      preLoaderRoute: typeof ApiOgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(home)/_layout': {
      id: '/(home)/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof homeLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(home)/_layout/': {
      id: '/(home)/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof homeLayoutIndexRouteImport
      parentRoute: typeof homeLayoutRoute
    }
    '/(home)/_layout/work': {
      id: '/(home)/_layout/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof homeLayoutWorkRouteImport
      parentRoute: typeof homeLayoutRoute
    }
    '/(home)/_layout/vault/tree-arithmetic/': {
      id: '/(home)/_layout/vault/tree-arithmetic/'
      path: '/vault/tree-arithmetic'
      fullPath: '/vault/tree-arithmetic'
      preLoaderRoute: typeof homeLayoutVaultTreeArithmeticIndexRouteImport
      parentRoute: typeof homeLayoutRoute
    }
    '/(home)/_layout/vault/ellty/': {
      id: '/(home)/_layout/vault/ellty/'
      path: '/vault/ellty'
      fullPath: '/vault/ellty'
      preLoaderRoute: typeof homeLayoutVaultElltyIndexRouteImport
      parentRoute: typeof homeLayoutRoute
    }
  }
}

interface homeLayoutRouteChildren {
  homeLayoutWorkRoute: typeof homeLayoutWorkRoute
  homeLayoutIndexRoute: typeof homeLayoutIndexRoute
  homeLayoutVaultElltyIndexRoute: typeof homeLayoutVaultElltyIndexRoute
  homeLayoutVaultTreeArithmeticIndexRoute: typeof homeLayoutVaultTreeArithmeticIndexRoute
}

const homeLayoutRouteChildren: homeLayoutRouteChildren = {
  homeLayoutWorkRoute: homeLayoutWorkRoute,
  homeLayoutIndexRoute: homeLayoutIndexRoute,
  homeLayoutVaultElltyIndexRoute: homeLayoutVaultElltyIndexRoute,
  homeLayoutVaultTreeArithmeticIndexRoute:
    homeLayoutVaultTreeArithmeticIndexRoute,
}

const homeLayoutRouteWithChildren = homeLayoutRoute._addFileChildren(
  homeLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  HealthRoute: HealthRoute,
  homeLayoutRoute: homeLayoutRouteWithChildren,
  ApiOgRoute: ApiOgRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
