/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as HealthRouteImport } from './routes/health'
import { Route as ApiOgRouteImport } from './routes/api/og'
import { Route as homeLayoutRouteImport } from './routes/(home)/_layout'
import { Route as homeLayoutIndexRouteImport } from './routes/(home)/_layout/index'
import { Route as homeLayoutWorkRouteImport } from './routes/(home)/_layout/work'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOgRoute = ApiOgRouteImport.update({
  id: '/api/og',
  path: '/api/og',
  getParentRoute: () => rootRouteImport,
} as any)
const homeLayoutRoute = homeLayoutRouteImport.update({
  id: '/(home)/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const homeLayoutIndexRoute = homeLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => homeLayoutRoute,
} as any)
const homeLayoutWorkRoute = homeLayoutWorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => homeLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/health': typeof HealthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/og': typeof ApiOgRoute
  '/work': typeof homeLayoutWorkRoute
  '/': typeof homeLayoutIndexRoute
}
export interface FileRoutesByTo {
  '/health': typeof HealthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/og': typeof ApiOgRoute
  '/work': typeof homeLayoutWorkRoute
  '/': typeof homeLayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/health': typeof HealthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/(home)/_layout': typeof homeLayoutRouteWithChildren
  '/api/og': typeof ApiOgRoute
  '/(home)/_layout/work': typeof homeLayoutWorkRoute
  '/(home)/_layout/': typeof homeLayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/health' | '/sitemap.xml' | '/api/og' | '/work' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/health' | '/sitemap.xml' | '/api/og' | '/work' | '/'
  id:
    | '__root__'
    | '/health'
    | '/sitemap.xml'
    | '/(home)/_layout'
    | '/api/og'
    | '/(home)/_layout/work'
    | '/(home)/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  HealthRoute: typeof HealthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  homeLayoutRoute: typeof homeLayoutRouteWithChildren
  ApiOgRoute: typeof ApiOgRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/og': {
      id: '/api/og'
      path: '/api/og'
      fullPath: '/api/og'
      preLoaderRoute: typeof ApiOgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(home)/_layout': {
      id: '/(home)/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof homeLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(home)/_layout/': {
      id: '/(home)/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof homeLayoutIndexRouteImport
      parentRoute: typeof homeLayoutRoute
    }
    '/(home)/_layout/work': {
      id: '/(home)/_layout/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof homeLayoutWorkRouteImport
      parentRoute: typeof homeLayoutRoute
    }
  }
}

interface homeLayoutRouteChildren {
  homeLayoutWorkRoute: typeof homeLayoutWorkRoute
  homeLayoutIndexRoute: typeof homeLayoutIndexRoute
}

const homeLayoutRouteChildren: homeLayoutRouteChildren = {
  homeLayoutWorkRoute: homeLayoutWorkRoute,
  homeLayoutIndexRoute: homeLayoutIndexRoute,
}

const homeLayoutRouteWithChildren = homeLayoutRoute._addFileChildren(
  homeLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  HealthRoute: HealthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  homeLayoutRoute: homeLayoutRouteWithChildren,
  ApiOgRoute: ApiOgRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
